### ISSUE TITLE
admin dashboard - sex up

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#103]
![image](https://cloud.githubusercontent.com/assets/5616668/8815982/b9cb7f78-2fee-11e5-9439-f199dd9792c5.png)
- WYSIWYG icon
- Fix arrangement (wysiwyg, etc)
- App gallery - create `+ add` button

**Comment by wightmike** [comment]
Could use this method to **expand**
http://wightdev.com/css/#menu

**Comment by wightmike** [comment]
![image](https://cloud.githubusercontent.com/assets/8368570/14729582/2440452c-080d-11e6-869e-7a6ae8fbed8c.png)

Latest

**Comment by wightmike** [comment]
Next. Level.
![image](https://cloud.githubusercontent.com/assets/8368570/16358356/dc62174e-3ade-11e6-8f4e-f31eff611006.png)
![image](https://cloud.githubusercontent.com/assets/8368570/16358358/edffb61e-3ade-11e6-8f92-80f5f8e744cb.png)
