### ISSUE TITLE
admin dashboard - location bug

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#106]
When I save changes to a nav item, that page breaks.

To fix the page, I need to select location: content and update the nav item.

The changes "saves" but location switches back to relbase.

This fixes the page...

![image](https://cloud.githubusercontent.com/assets/8368570/8867305/a5967d16-3195-11e5-83dc-583d19f3df74.png)

**Comment by bioshazard** [comment]
I fixed this in https://github.com/eflip/LittlefootCMS/pull/122 but had to add the wysiwyg because it was saved in that branch. gonna open a separate request for you to make it look pretty
