### ISSUE TITLE
Better theming system

### ISSUE THREAD

**Issue by ghost** [eflip/LittlefootCMS#109]
You could think about better theming system, actual one isn't very usable.

**Comment by wightmike** [comment]
What would you like to see?

**Comment by bioshazard** [comment]
Made some progress in https://github.com/eflip/LittlefootCMS/issues/12 where I replaced the %string% variables system with `$this->lf->printContent('nav')`. ive got a doc started at http://littlefootcms.com/manual/Littlefoot

**Comment by bioshazard** [comment]
if you have any specific feedback about what you would like to see, please let us know!
