### ISSUE TITLE
lf css - border-radius 0

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#110]
I think it would be cool to add something like

`.squared * { border-radius: 0 !important; }`

I did it to one of my apps and it looks SWEET. I also like it in the admin. Just square off EVERYTHING. Very Metro.

**Comment by bioshazard** [comment]
and `.squared { br0! }`

**Comment by bioshazard** [comment]
looks good on github too XD

![image](https://cloud.githubusercontent.com/assets/5616668/8946794/cb1f338c-3561-11e5-8aff-3b2ad8a1fa87.png)

**Comment by wightmike** [comment]
https://github.com/eflip/LittlefootCMS/issues/113
