### ISSUE TITLE
users - user profiles

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#111]
Users should be able to update their profile information (email, password, username, avatar, etc.)

Currently you must have access to the users area in admin to do so. Front-end users cannot edit their information or even update their password.

**Comment by bioshazard** [comment]
https://github.com/eflip/LittlefootCMS/tree/userprofile

otw

**Comment by bioshazard** [comment]
https://github.com/eflip/LittlefootCMS/pull/128
