### ISSUE TITLE
system - string replacement

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#12]
Are we making the move?

%content%

or

$content

**Comment by bioshazard** [comment]
Yes. We will be moving to php based content replacement. This will likely
involve the introduction of a template system. Such a move will address a
long standing I have had with templating in general.

**Comment by kripplek** [comment]
#templateObject

**Comment by bioshazard** [comment]
I left the string replacement, but now the lf object is more usable in this regard. I need only to add in getters for the needed strings like $lf->skinBase() etc

**Comment by bioshazard** [comment]
spoke to kyle about saving short code as actual PHP (like markdown to html)

**Comment by bioshazard** [comment]
https://github.com/eflip/LittlefootCMS/pull/138

**Comment by bioshazard** [comment]
still need to do admin, but im pushing that back to a later milestone

**Comment by bioshazard** [comment]
https://github.com/eflip/XV/pull/6

**Comment by bioshazard** [comment]
need to pull latest XV and littlefoot

**Comment by bioshazard** [comment]
Yea wow, still need to apply this to many places. Also need to make a decision about how to document and organize things.

**Comment by bioshazard** [comment]
This has been replaced by the [template system](http://littlefootcms.com/docs/classes/lf.template.html)
