### ISSUE TITLE
admin dashboard wysiwyg

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#123]
plz make this prettier

![image](https://cloud.githubusercontent.com/assets/5616668/9158004/7857eea2-3edd-11e5-9005-54e7d2c0369f.png)

**Comment by wightmike** [comment]
![image](https://cloud.githubusercontent.com/assets/8368570/14836804/ee5994ea-0be0-11e6-9937-d2e2f0141fa9.png)

**Comment by wightmike** [comment]
this was cleaned up
