### ISSUE TITLE
lfcss - blockquote

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#124]
there is no default formatting for block quote.

I would like something simple like this

https://css-tricks.com/snippets/css/simple-and-nice-blockquote-styling/

We can talk about specific classes to made further changes, but there should be a default CSS for blockquote without class for things like markdown.

**Comment by wightmike** [comment]
http://wightdev.com/css/#blockquotes

![image](https://cloud.githubusercontent.com/assets/8368570/9373701/4101e7ce-46bb-11e5-9793-f3a49a124451.png)

```
<blockquote>
    <p>Cras vitae mattis nibh. Praesent aliquet laoreet felis, quis tincidunt lorem volutpat a. Pellentesque tempor ante nulla, id pulvinar quam vehicula ut. Sed id nibh et tortor porttitor aliquam vitae vel nisi.</p>
</blockquote>
```

**Comment by wightmike** [comment]
completed
https://github.com/eflip/LittlefootCMS/pull/125
