### ISSUE TITLE
admin login - link to front page

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#127]
The admin login needs a link to the front page of your site.

"<- Back to MyDomain.com"

![image](https://cloud.githubusercontent.com/assets/8368570/10328615/389cdaa4-6c85-11e5-8887-6f92ec34d5cf.png)

**Comment by kripplek** [comment]
Use php. `<?php echo $SERVER['HTTP_HOST'] ?>`

**Comment by kripplek** [comment]
Inb4 put it in the href.

**Comment by wightmike** [comment]
nvm
