### ISSUE TITLE
system - debug and head

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#13]
lf/system/littlefoot.php

lines 855 - 900 are pretty nasty

**Comment by wightmike** [comment]
I'll get rid of the inline style and lf.css it up.

**Comment by wightmike** [comment]
Waiting on fix here: https://github.com/eflip/LittlefootCMS/issues/133

**Comment by wightmike** [comment]
Debug actually looks fine on the front end now.

JOE, make your code prettier.

**Comment by bioshazard** [comment]
Is this still a problem? I believe it got swept up in 2.0

**Comment by wightmike** [comment]
debug works perfectly now

![image](https://cloud.githubusercontent.com/assets/8368570/16358413/418bbae8-3ae0-11e6-8562-4fdf7ecebc81.png)
