### ISSUE TITLE
Debug shows when off

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#133]
Debug still shows in page source when set to **off**.
![image](https://cloud.githubusercontent.com/assets/8368570/11356278/5b1b7f0c-922a-11e5-861c-0734de0a7a40.png)

![image](https://cloud.githubusercontent.com/assets/8368570/11356287/67264ffc-922a-11e5-8648-ec93789b0d84.png)

**Comment by wightmike** [comment]
Ironically when I set debug to **on** it doesn't show on the front end.

**Comment by bioshazard** [comment]
fixed https://github.com/eflip/LittlefootCMS/commit/dca27a40559aa00581a6f9d6440dc3478c231f02
