### ISSUE TITLE
Post install issues

### ISSUE THREAD

**Issue by claybruh** [eflip/LittlefootCMS#140]
After a fresh install, the index loaded a white page with only the following error:

Parse error: syntax error, unexpected '/' in /home/clayton/public_html/cockybadger/lf/apps/pages/index.php on line 45

The error was alleviated by browsing to the dashboard, and updating the 'pages' app through the store. When running the update option, nothing changes on the page to let you know the update has completed, and the update option is left on the page. Screenshot after running the update: ![screenshot](http://i.imgur.com/lYHdlbE.png)

This also breaks the XV skin after the update
![screenshot](http://i.imgur.com/HOtLreT.png)

**Comment by claybruh** [comment]
Also, the XV skin does work after an update on it as well.

**Comment by bioshazard** [comment]
I updated all the apps and merged dev into master, released it live and automated installation deployment for quick testing upon each release so we know it doesnt break at installation.
