### ISSUE TITLE
Untitled pages

### ISSUE THREAD

**Issue by claybruh** [eflip/LittlefootCMS#141]
When creating a new page in the 'pages' app without a title, it leaves you without the option of editing the page without a direct link to it. Would it be possible for LF to automatically label untitled pages as 'untitled1, untitled2, etc' so that they are still editable, yet leave the untitled title off the page on the front end? Alternatively, an option on the backend to disable front end titles for that specific page would suffice.

![screenshot](http://i.imgur.com/4tfm14H.png)

title:
![screenshot](http://i.imgur.com/dyN9AG3.png)

no title
![screenshot](http://i.imgur.com/x1svXGH.png)

**Comment by bioshazard** [comment]
rekt https://github.com/eflip/Pages/commit/45466bc1de0f036464796205c839613a74b8b5d7

**Comment by bioshazard** [comment]
pushed to store

**Comment by claybruh** [comment]
Would it be possible to add the other features I mentioned? The ability to title the page so it's visible on the list, yet be able to remove the title from the front end?

![screenshot](https://camo.githubusercontent.com/ba91ac360a734a779d5a95017501d0c10fd7f442/687474703a2f2f692e696d6775722e636f6d2f64794e394147332e706e67)

**Comment by bioshazard** [comment]
https://github.com/eflip/Pages/blob/c94793093f5012b4cd4defb752735be4a8a135e7/index.php#L10

In the latest version of the pages app, the title is only shown in the tab. So now you have to specifically put a header in the page body

**Comment by claybruh** [comment]
Mike, please remove the header tags per our discussion

**Comment by wightmike** [comment]
This is already fixed in the latest version of pages. You need to update your pages app.
