### ISSUE TITLE
XVI

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#144]
2016 coming up. What is next year's theme?

**Comment by wightmike** [comment]
I would like to revisit the naming convention for the theme. Open to ideas.

**Comment by wightmike** [comment]
I'm considering going back to 'Fresh', and ditching a numerical nomenclature.

**Comment by wightmike** [comment]
It is now called **LittlefootCSS** 4eva

**Comment by claybruh** [comment]
http://i.imgur.com/vVEnegd.gif
