### ISSUE TITLE
header top margin overlap

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#145]
I often put links above a header, but the bottom half is overlapped and makes me misclick. Please remove the overlap.

![image](https://cloud.githubusercontent.com/assets/5616668/11791488/51746c84-a26f-11e5-832c-9fdb94672a3e.png)

**Comment by bioshazard** [comment]
I should mention that I moved some stuff around in dev

https://github.com/eflip/LittlefootCMS/commit/ae5c5df4cb0b4b7790f7dad73f11a115c0c27129

**Comment by wightmike** [comment]
I would request that you stop adding links above headers. Headers should be at the top, and "back to..." links can go below them.

**Comment by bioshazard** [comment]
# Headers

Usually dont overlap the text above

## Them

I will stop, but what happens when you have two sections one after the other?

**Comment by wightmike** [comment]
![image](https://cloud.githubusercontent.com/assets/8368570/14729890/c6c5ca54-080f-11e6-9fee-179ef72c54df.png)

![image](https://cloud.githubusercontent.com/assets/8368570/14730019/d94cd874-0810-11e6-8b27-237f779bfcd2.png)

I believe that if text is placed within an appropriate element such as a `<p>` or a `<div>` it will work fine. 

Leaving the text bare or putting it in a `<span>` **will not** work appropriately.
