### ISSUE TITLE
Docs - lfcss cheat sheet

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#147]
Finalize this wiki page.

http://littlefootcms.com/manual/Cheat+Sheet

**Comment by bioshazard** [comment]
Or consolidate into http://littlefootcms.com/theme/

**Comment by claybruh** [comment]
The anchor tags are broken on http://littlefootcms.com/theme/ click a link off to the right

**Comment by wightmike** [comment]
This is the cheatsheet: http://wightdev.com/css

I'll copy / paste for now.

**Comment by bioshazard** [comment]
Depends on https://github.com/lfcms/LittlefootCMS/issues/216

**Comment by wightmike** [comment]
Website needs to be updated for cheat sheet to work.

**Comment by bioshazard** [comment]
lfcms.com has been updated to latest version 2. now uses git for version control.

**Comment by wightmike** [comment]
Done.
http://littlefootcms.com/theme/
