### ISSUE TITLE
need nav dropdown caret when children are present

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#149]
![image](https://cloud.githubusercontent.com/assets/5616668/11946903/9d200f4e-a82d-11e5-88d5-9b789f3efbc6.png)

**Comment by wightmike** [comment]
This is really more of a programmatic change.

If nav has children, add the caret icon to the parent nav link.

Example:

`<a>Parent Nav Link <i class="fa fa-caret-down"></i></a>`

**Comment by bioshazard** [comment]
https://github.com/eflip/LittlefootCMS/commit/45e4c367dd853bb28ef843dcffec0c5d5563fd5c
