### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by claybruh** [eflip/LittlefootCMS#152]
Fatal error: Call to a member function fetchall() on a non-object in /home/clayton/public_html/cockybadger/lf/system/lib/recovery/upgrade.php on line 16

http://claytonfryar.com/cockybadger

**Comment by claybruh** [comment]
The upgrade littlefoot button works, but not this part

Run lf/system/lib/recovery/upgrade.php

Do both of them perform the same task?

**Comment by bioshazard** [comment]
Fixed Upgrade and Installer https://github.com/eflip/LittlefootCMS/pull/165

**Comment by bioshazard** [comment]
Turned the upgrade link into a button called "check database" so its more clear
