### ISSUE TITLE
New Skin feature update

### ISSUE THREAD

**Issue by claybruh** [eflip/LittlefootCMS#154]
i'm playing around with the skin system and tried to create a brand new one, which generated the following when set to default
![image](http://i.imgur.com/6B7FtL1.png)

however it seems like the code included in the skin has the wrong path for the css. XV has the following

```
<link rel="stylesheet" type="text/css" href="<?=$this->lf->getSkinBase();?>/css/custom.css" />
```

while the newly  create skin has this:

```
<link rel="stylesheet" type="text/css" href="%{skinbase}%/css/styles.css" />
```

**Comment by bioshazard** [comment]
Fixed for 2.0 in https://github.com/eflip/LittlefootCMS/commit/d0ddbdfc8540f4fff88a6075ee4b0150744de24f
