### ISSUE TITLE
LF Admin - Access - Selected Tab

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#168]
Please add a highlight to the selected tab.

![image](https://cloud.githubusercontent.com/assets/5616668/13866809/6d00205a-ec8f-11e5-9026-af832cf6559d.png)

**Comment by wightmike** [comment]
![image](https://cloud.githubusercontent.com/assets/8368570/14728323/89f21852-0801-11e6-851a-6a81893683b5.png)

fixed
