### ISSUE TITLE
lf admin - Skin Manager Items are too big

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#170]
1920x1080 and I see 2 skins and the tip tops of two others. I think we should reduce it to rows.

![image](https://cloud.githubusercontent.com/assets/5616668/14191770/c4099efc-f767-11e5-88cf-5d35ebc5e4e8.png)

**Comment by wightmike** [comment]
Completed.
https://github.com/eflip/LittlefootCMS/pull/172
