### ISSUE TITLE
LF Admin - Access - Users tab error

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#173]
```
Fatal error: Class 'db\lf_users' not found in /home/wightdev/public_html/lf/system/admin/controller/acl.php on line 42
```

This happens when I click on the `Users` tab.

Noticed when working on the following issue:
https://github.com/eflip/LittlefootCMS/issues/168

**Comment by bioshazard** [comment]
Fixed in https://github.com/eflip/LittlefootCMS/commit/9f892fd777748efc3f57eba691d30398373f03be
