### ISSUE TITLE
Users - Add labels for user editor fields

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#175]
![image](https://cloud.githubusercontent.com/assets/5616668/14826982/43cd8ce8-0bae-11e6-8198-ec2ca4326219.png)

**Comment by wightmike** [comment]
Alriiiight

**Comment by wightmike** [comment]
This was done:
![image](https://cloud.githubusercontent.com/assets/8368570/25788364/8d4c1722-3376-11e7-900c-85275106d66e.png)

But I'm gonna make it better...

**Comment by wightmike** [comment]
Meh, I lied...

Just took care of spacing.

![image](https://cloud.githubusercontent.com/assets/8368570/25789222/ef29f562-337c-11e7-88cf-aef2af3bc17e.png)


Might look into fancier input boxes in the future for things like login and search.
