### ISSUE TITLE
LF Admin - WYSIWYG

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#178]
- Needs all functionality of the current dashboard
- Adding apps to nav items and creating new nav items
- Should be able to delete the current Dashboard once complete

**Comment by wightmike** [comment]
Styling issue is here:
https://github.com/eflip/LittlefootCMS/issues/123

**Comment by bioshazard** [comment]
done. just needs style finalization

**Comment by bioshazard** [comment]
That can be closed after we merge https://github.com/eflip/LittlefootCMS/tree/wysiwyg3

**Comment by wightmike** [comment]
good for now, merged
