### ISSUE TITLE
Consolidate Preview Into Nav select

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#189]
I moved preview up to the top and consolidated "navigation". I love it. I also like the full screen button. Thoughts?

![image](https://cloud.githubusercontent.com/assets/5616668/16360459/eb7ce96c-3b32-11e6-92e9-a2e7f8e65646.png)

**Comment by wightmike** [comment]
Nah, remove Preview

**Comment by wightmike** [comment]
Also note that Dashboard is changing entirely:
https://github.com/lfcms/LittlefootCMS/issues/191

**Comment by bioshazard** [comment]
Can we make it drop-down hidden like the hidden navigation items? Or do we straight up want it gone?

**Comment by wightmike** [comment]
Hold onto the code for later. Right now I find it superfluous and confusing (non-intuitive). It takes up a lot of space on a page that shouldn't be very big. I could go on but I'm not trying to "shit on" the idea. I just don't think it's necessary or appropriate for the Nav page at this time. The navigation items can be seen at the top of the page. Seeing them "in action" doesn't change much or make anything easier to use really. Yes you can preview the site, but the Navigation settings is hardly where I would go to do such a thing intuitively.

Ultimately, I can only say that it doesn't "feel" right or natural in its current form. A dropdown would only add complexity to something I find overly complex. It might be more usable in a wysiwyg quick-edit format down the road. This would more likely be associated with the **skins page**.

**Comment by bioshazard** [comment]
Moved in https://github.com/lfcms/LittlefootCMS/pull/208 from Nav to new hidden [experimental](https://github.com/lfcms/LittlefootCMS/blob/development/lf/system/admin/controller/experimental.php#L31) admin page

![image](https://cloud.githubusercontent.com/assets/5616668/25212011/0582fb7c-2556-11e7-8456-cce45aab24fb.png)
