### ISSUE TITLE
Admin Users - pending users can log in

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#190]
Users with `pending` status are still able to log in, but they shouldn't be.

**Comment by wightmike** [comment]
Also **RIP** Edit User function

Warning: Invalid argument supplied for foreach() in /home/wightdev/public_html/lf/system/lib/orm.php on line 858

**Comment by bioshazard** [comment]
Resolved in https://github.com/lfcms/LittlefootCMS/pull/201

Check out that link for screenshots of some updates to interface
