### ISSUE TITLE
Admin Navigation - URL

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#191]
Our new dashboard uses `admin/wysiwyg` as the url, and it should now use `admin/dashboard`.

**Comment by wightmike** [comment]
Navigation is currently accessed via Dashboard in the Admin Menu. 

Navigation needs its own Menu item called "Navigation",

**Comment by bioshazard** [comment]
Fixed in https://github.com/lfcms/LittlefootCMS/pull/202
