### ISSUE TITLE
Admin Media - we need a file manager

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#192]
There is currently no file manager in Littlefoot. We desperately need one.
- Images
- Videos
- .doc, .pdf, .xls, etc

**Comment by bioshazard** [comment]
![image](https://cloud.githubusercontent.com/assets/5616668/25078817/a46eb41e-2304-11e7-8fd0-2e45fe29f1c4.png)

**Comment by bioshazard** [comment]
![image](https://cloud.githubusercontent.com/assets/5616668/25078826/bdfea88a-2304-11e7-8cdf-b5974add682e.png)

**Comment by bioshazard** [comment]
![image](https://cloud.githubusercontent.com/assets/5616668/25078832/d51e1a78-2304-11e7-860e-36cea43732a9.png)

**Comment by bioshazard** [comment]
Addressed in https://github.com/lfcms/LittlefootCMS/pull/204

Turning this over to Mike to beautify.

**Comment by wightmike** [comment]
Styled up a tad. Good for now.

**Delete button does not work!**

**Comment by bioshazard** [comment]
delete button has been implemented in development.

do you intend to do more styling to this? or should this issue just be closed?

**Comment by wightmike** [comment]
Just remove this:

```
TODO: DRAGON DROP // ty http://tutorialzine.com/2011/09/html5-file-upload-jquery-php/
```
and we're good for now.

**Comment by bioshazard** [comment]
Removal pending https://github.com/lfcms/LittlefootCMS/issues/217

**Comment by bioshazard** [comment]
Resolved https://github.com/lfcms/LittlefootCMS/commit/de7cc5cb10a0995e6565d3ce72385b4054a86700
