### ISSUE TITLE
Admin Dashboard - Widgets

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#193]
Dashboard will feature widgets for content management of able apps.

**Comment by bioshazard** [comment]
Implemented in https://github.com/lfcms/LittlefootCMS/pull/202

Update your blog and pages apps to see it in action!

**Comment by bioshazard** [comment]
Make it pretty!

**Comment by wightmike** [comment]
Need to figure out what to do with this:
![image](https://cloud.githubusercontent.com/assets/8368570/25925109/8abdb7aa-35b4-11e7-8244-db5593e1299b.png)

* Is it even necessary?
* Would these links be better of in the widgets themselves?

**Comment by bioshazard** [comment]
The function of this is to display all the navigation items where an app is linked so you can quickly go to it for modification. It may be more appropriate in the navigation page or removed entirely... I can always recreate it immediately... I will just remove it.

https://github.com/lfcms/LittlefootCMS/commit/76bee3fb0a1cf6863a1b4af33c7623aceeaf0458

**Comment by bioshazard** [comment]
Let me know if you have any interest in linking them in the widgets. I did that originally, but I felt it was better on the right. I worry now that I am falling back on my old bad habit of injected unless nonsense that an end user has no use for.

**Comment by wightmike** [comment]
We can revisit this later.
