### ISSUE TITLE
Docs - How to Create a Skin

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#195]
You know what to do:

http://littlefootcms.com/manual/

->

https://github.com/lfcms/LittlefootCMS/wiki

**Comment by bioshazard** [comment]
User Manual published: https://github.com/lfcms/LittlefootCMS/wiki/Littlefoot-User-Manual

Dev manual pending

**Comment by bioshazard** [comment]
Dev manual implemented. Skin explanation is all that is left, unless you do not intend to have a wiki on the topic. Leaving to your ownership, though you can tackle that next milestone given the short notice.

https://github.com/lfcms/LittlefootCMS/wiki/Littlefoot-Developer-Guide#21-skins

**Comment by bioshazard** [comment]
I also updated http://littlefootcms.com/manual/ to redirect to github wiki

**Comment by wightmike** [comment]
Update the following link to show how skins are created / used:

https://github.com/lfcms/LittlefootCMS/wiki/Developing-Skins
