### ISSUE TITLE
Admin Nav - Review Interface

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#196]
* Does everything work?
* Where should it all go?

**Comment by bioshazard** [comment]
- Everything does work.

**Comment by bioshazard** [comment]
I will review everything to make sure it works.

**Comment by bioshazard** [comment]
It all works now. Switched to using IDs for menu item selection. Handing this back to you to deal with reviewing the interface design. I vote we move or fork this to GBoF.

**Comment by bioshazard** [comment]
looks great. works great.
