### ISSUE TITLE
Review User Feedback

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#197]
https://www.reddit.com/r/cms/comments/601cfn/i_wrote_this_php_based_cmsframework_from_scratch/

Break this up into issues.

**Comment by bioshazard** [comment]
- Theme copy name weirdness: https://github.com/lfcms/LittlefootCMS/issues/221
- Theme wysiwyg: https://github.com/lfcms/LittlefootCMS/issues/222
- Theme color management: https://github.com/lfcms/LittlefootCMS/issues/223
- The rest was either implemented or goes against our existing design decisions.
- This task was to break the feedback into issues.
