### ISSUE TITLE
LF Admin

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#205]
rename files in lf/system/admin

There are a bunch of confusing dashboard files. Now that dashboard and navigation are separate, we should have these all renamed according to their respective roles.

**Comment by bioshazard** [comment]
- Delete things that aren't in use any more
- Rename dashboard partials to navigation partials
- Document naming convention standard
- Rename all files to meet naming convention standard

**Comment by bioshazard** [comment]
🎵 I can see clearly now, the cruft is gone 🎵

![image](https://user-images.githubusercontent.com/5616668/27160248-ca3c2298-5140-11e7-8290-e6716514cd61.png)
