### ISSUE TITLE
plugins - notifications

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#29]
Notices should be stored in a database.

Seen status tracked per user.

x (delete) can close a notice and mark as seen.

**Comment by bioshazard** [comment]
notice works in session, but no database for acknowledgement yet

**Comment by bioshazard** [comment]
just gonna add an X to clear them from the screen

**Comment by bioshazard** [comment]
this can be a fancy notice plugin that uses the built in notice system
