### ISSUE TITLE
lf.css - dropdown nav

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#3]
We need styling for nav child items to create dropdown navigation buttons

**Comment by wightmike** [comment]
Dropdown navs are now working.

.main_nav works with dropdowns by default.

thinking about making a .dropdown class as well.

**Comment by wightmike** [comment]
At the moment, second level children are indented and their text is made smaller. Open to suggestions.

http://wightdev.com/

**Comment by wightmike** [comment]
latest pushed to development

**Comment by bioshazard** [comment]
so hawt. I love it!
