### ISSUE TITLE
mobile.css - menu button / dropdown

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#43]
Navigation and other menus should collapse for mobile and use a menu button to expand.

**Comment by wightmike** [comment]
Closed https://github.com/eflip/LittlefootCMS/issues/2 as it was a duplicate of this issue.

**Comment by bioshazard** [comment]
do eet https://css-tricks.com/responsive-menu-concepts/

**Comment by wightmike** [comment]
Could use this method:
http://wightdev.com/css/#menu

**Comment by wightmike** [comment]
YESSSS

![image](https://cloud.githubusercontent.com/assets/8368570/11455158/31eeedd4-961d-11e5-95c9-d30b82d487bb.png)

![image](https://cloud.githubusercontent.com/assets/8368570/11455159/3f05e4d2-961d-11e5-8ab1-8fa192428dc6.png)
