### ISSUE TITLE
lfcss - fXX class, etc

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#48]
I would like to be able to go

```
<span class="f24">Big Text</span>
```

and have the resulting output apply `font-size: 24px;` to that element.

**Comment by bioshazard** [comment]
And like with hXX, it should go like f12 -> f36 or something.

It would be nice to change the `<html>` font size like this:

`<html class="lf f24">`

**Comment by wightmike** [comment]
This is done.

https://github.com/eflip/LittlefootCMS/pull/75/files
