### ISSUE TITLE
lf.css - icon font

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#6]
I need to integrate an icon font to be used in lf.css

**Comment by wightmike** [comment]
font awesome isn't working.. hmmm

**Comment by bioshazard** [comment]
got a link to the commit you are working with? or is it on a branch in 
your local repo?

**Comment by wightmike** [comment]
Here's the commit.

https://github.com/eflip/LittlefootCMS/commit/2384f4bd3122d841f6a873e71ec1d396156cfbc5

I used it at the bottom of the http://wightdev.com homepage.

**Comment by bioshazard** [comment]
Strange, it shows in firebug as just blocks. Not sure what to tell ya :\

**Comment by wightmike** [comment]
fixed, we now have awesome font icons.

https://github.com/eflip/LittlefootCMS/commit/8036a8b014acaba7be4e1b796538ae47942bf0f3
https://github.com/eflip/LittlefootCMS/commit/2384f4bd3122d841f6a873e71ec1d396156cfbc5
