### ISSUE TITLE
Invalid argument supplied 

### ISSUE THREAD

**Issue by ghost** [eflip/LittlefootCMS#69]
There's an error at blog_admin.home.php, at line 17. It occur only when no category is created.

Full error issue:
Invalid argument supplied for foreach() in C:\xampp\htdocs\lf\apps\blog\view\blog_admin.home.php on line 17

**Comment by kripplek** [comment]
This issue was opened in the wrong repository. That file is apart of the blog app. I have created a fix and a PR. Should be good soon. Thanks for reporting.

**Comment by bioshazard** [comment]
w3bariak,

Thank you for submitting this issue. I have applied https://github.com/eflip/Blog/pull/7 (thanks k-sorrels!) along with a few other updates and released the latest blog. You should be able to delete the blog app and download the latest one from the Store (on the left in the admin). Please let me know if you run into any further issues.
