### ISSUE TITLE
pages - ace editor

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#73]
Pages should use the Ace editor and allow for Markdown as well.

**Comment by bioshazard** [comment]
https://github.com/eflip/Pages/commit/c94793093f5012b4cd4defb752735be4a8a135e7

**Comment by bioshazard** [comment]
Did it to Wiki too

https://github.com/eflip/Wiki/commit/e594cbc2005c9dfdaf0785e3b290b2a29b5e3497
