### ISSUE TITLE
lfcss - select-box sizing

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#83]
The select boxes are not sizing properly. They should be the same size as text inputs.

**Comment by wightmike** [comment]
Related issue:
https://github.com/eflip/LittlefootCMS/issues/36

**Comment by wightmike** [comment]
I am not seeing this issue on my computer. Joe, do you notice the select fields being the wrong size compared to input fields? They look the same size in Chrome and FF for me.

**Comment by bioshazard** [comment]
idk man
