### ISSUE TITLE
lf/system/admin/view/login.php - Is it needed?

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#84]
lf/system/admin/view/login.php seems redundant since this is actually located in admin/skin/default/login

**Comment by bioshazard** [comment]
Nope, its loads from the admin folder now

```
    /home/bios/public_html/littlefoot/lf/system/admin/index.php 
    /home/bios/public_html/littlefoot/lf/system/admin/skin/default/login.php    
```

**Comment by bioshazard** [comment]
cleared up in https://github.com/eflip/LittlefootCMS/commit/2f34f4f2fb50c507a28e3585a34a11a3bddecf8d
