### ISSUE TITLE
admin store - vlist

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#96]
vlist for zip url install

![image](https://cloud.githubusercontent.com/assets/5616668/8815845/eb785336-2fec-11e5-8bc7-cd6faeb302da.png)

**Comment by wightmike** [comment]
![image](https://cloud.githubusercontent.com/assets/8368570/11356156/ea7661fa-9228-11e5-99af-e89de5b79d84.png)
Fixed.
