### ISSUE TITLE
admin skin - new skin padding

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#98]
![image](https://cloud.githubusercontent.com/assets/5616668/8816248/49adffb4-2ff2-11e5-9997-2d0ca1f8b525.png)

fix it!

**Comment by wightmike** [comment]
![image](https://cloud.githubusercontent.com/assets/8368570/11355899/a26cd95e-9226-11e5-8cec-af7ac20791a9.png)
Fixed
