### ISSUE TITLE
admin skin - check

### ISSUE THREAD

**Issue by bioshazard** [eflip/LittlefootCMS#99]
![image](https://cloud.githubusercontent.com/assets/5616668/8816297/08ca2cce-2ff3-11e5-8b31-ccab3ce6ea63.png)

check mark should be green

**Comment by bioshazard** [comment]
also, update the screenshot for the new blue default

**Comment by wightmike** [comment]
Using power symbol now, and it's green when active.

![image](https://cloud.githubusercontent.com/assets/8368570/16358384/9915ad88-3adf-11e6-9947-dfeb52accab4.png)
